name: Integration
on:
 pull_request:
  branches:
    - main
jobs:
   build_application:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - uses: actions/setup_node@v2
       - name: Install dependencies
         run: npm install
       - name: Build application
         run: npm run build
   unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup_node@v2
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run test

